development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: blog_backbone
  pool: 3
  username: root
  password:
  host: 127.0.0.1

test:
  <<: *development
  database: blog_backbone_test
